// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping.proto

package org.micoli.phone.ccphone.remote.messages;

public final class PingPong {
  private PingPong() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 processingTime = 1;
    boolean hasProcessingTime();
    int getProcessingTime();
    
    // required int32 pongDataLength = 2;
    boolean hasPongDataLength();
    int getPongDataLength();
  }
  public static final class Ping extends
      com.google.protobuf.GeneratedMessage
      implements PingOrBuilder {
    // Use Ping.newBuilder() to construct.
    private Ping(Builder builder) {
      super(builder);
    }
    private Ping(boolean noInit) {}
    
    private static final Ping defaultInstance;
    public static Ping getDefaultInstance() {
      return defaultInstance;
    }
    
    public Ping getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.micoli.phone.ccphone.remote.messages.PingPong.internal_static_Ping_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.micoli.phone.ccphone.remote.messages.PingPong.internal_static_Ping_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 processingTime = 1;
    public static final int PROCESSINGTIME_FIELD_NUMBER = 1;
    private int processingTime_;
    public boolean hasProcessingTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getProcessingTime() {
      return processingTime_;
    }
    
    // required int32 pongDataLength = 2;
    public static final int PONGDATALENGTH_FIELD_NUMBER = 2;
    private int pongDataLength_;
    public boolean hasPongDataLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPongDataLength() {
      return pongDataLength_;
    }
    
    private void initFields() {
      processingTime_ = 0;
      pongDataLength_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasProcessingTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPongDataLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, processingTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, pongDataLength_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, processingTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pongDataLength_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.micoli.phone.ccphone.remote.messages.PingPong.Ping prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.micoli.phone.ccphone.remote.messages.PingPong.PingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.micoli.phone.ccphone.remote.messages.PingPong.internal_static_Ping_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.micoli.phone.ccphone.remote.messages.PingPong.internal_static_Ping_fieldAccessorTable;
      }
      
      // Construct using org.micoli.phone.ccphone.remote.messages.PingPong.Ping.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        processingTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pongDataLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.micoli.phone.ccphone.remote.messages.PingPong.Ping.getDescriptor();
      }
      
      public org.micoli.phone.ccphone.remote.messages.PingPong.Ping getDefaultInstanceForType() {
        return org.micoli.phone.ccphone.remote.messages.PingPong.Ping.getDefaultInstance();
      }
      
      public org.micoli.phone.ccphone.remote.messages.PingPong.Ping build() {
        org.micoli.phone.ccphone.remote.messages.PingPong.Ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.micoli.phone.ccphone.remote.messages.PingPong.Ping buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.micoli.phone.ccphone.remote.messages.PingPong.Ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.micoli.phone.ccphone.remote.messages.PingPong.Ping buildPartial() {
        org.micoli.phone.ccphone.remote.messages.PingPong.Ping result = new org.micoli.phone.ccphone.remote.messages.PingPong.Ping(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.processingTime_ = processingTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pongDataLength_ = pongDataLength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.micoli.phone.ccphone.remote.messages.PingPong.Ping) {
          return mergeFrom((org.micoli.phone.ccphone.remote.messages.PingPong.Ping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.micoli.phone.ccphone.remote.messages.PingPong.Ping other) {
        if (other == org.micoli.phone.ccphone.remote.messages.PingPong.Ping.getDefaultInstance()) return this;
        if (other.hasProcessingTime()) {
          setProcessingTime(other.getProcessingTime());
        }
        if (other.hasPongDataLength()) {
          setPongDataLength(other.getPongDataLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasProcessingTime()) {
          
          return false;
        }
        if (!hasPongDataLength()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              processingTime_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pongDataLength_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 processingTime = 1;
      private int processingTime_ ;
      public boolean hasProcessingTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getProcessingTime() {
        return processingTime_;
      }
      public Builder setProcessingTime(int value) {
        bitField0_ |= 0x00000001;
        processingTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearProcessingTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        processingTime_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 pongDataLength = 2;
      private int pongDataLength_ ;
      public boolean hasPongDataLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPongDataLength() {
        return pongDataLength_;
      }
      public Builder setPongDataLength(int value) {
        bitField0_ |= 0x00000002;
        pongDataLength_ = value;
        onChanged();
        return this;
      }
      public Builder clearPongDataLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pongDataLength_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Ping)
    }
    
    static {
      defaultInstance = new Ping(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Ping)
  }
  
  public interface PongOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes pongData = 1;
    boolean hasPongData();
    com.google.protobuf.ByteString getPongData();
  }
  public static final class Pong extends
      com.google.protobuf.GeneratedMessage
      implements PongOrBuilder {
    // Use Pong.newBuilder() to construct.
    private Pong(Builder builder) {
      super(builder);
    }
    private Pong(boolean noInit) {}
    
    private static final Pong defaultInstance;
    public static Pong getDefaultInstance() {
      return defaultInstance;
    }
    
    public Pong getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.micoli.phone.ccphone.remote.messages.PingPong.internal_static_Pong_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.micoli.phone.ccphone.remote.messages.PingPong.internal_static_Pong_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes pongData = 1;
    public static final int PONGDATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString pongData_;
    public boolean hasPongData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getPongData() {
      return pongData_;
    }
    
    private void initFields() {
      pongData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPongData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, pongData_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, pongData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Pong parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Pong parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Pong parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Pong parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Pong parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Pong parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Pong parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Pong parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Pong parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.micoli.phone.ccphone.remote.messages.PingPong.Pong parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.micoli.phone.ccphone.remote.messages.PingPong.Pong prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.micoli.phone.ccphone.remote.messages.PingPong.PongOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.micoli.phone.ccphone.remote.messages.PingPong.internal_static_Pong_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.micoli.phone.ccphone.remote.messages.PingPong.internal_static_Pong_fieldAccessorTable;
      }
      
      // Construct using org.micoli.phone.ccphone.remote.messages.PingPong.Pong.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        pongData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.micoli.phone.ccphone.remote.messages.PingPong.Pong.getDescriptor();
      }
      
      public org.micoli.phone.ccphone.remote.messages.PingPong.Pong getDefaultInstanceForType() {
        return org.micoli.phone.ccphone.remote.messages.PingPong.Pong.getDefaultInstance();
      }
      
      public org.micoli.phone.ccphone.remote.messages.PingPong.Pong build() {
        org.micoli.phone.ccphone.remote.messages.PingPong.Pong result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.micoli.phone.ccphone.remote.messages.PingPong.Pong buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.micoli.phone.ccphone.remote.messages.PingPong.Pong result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.micoli.phone.ccphone.remote.messages.PingPong.Pong buildPartial() {
        org.micoli.phone.ccphone.remote.messages.PingPong.Pong result = new org.micoli.phone.ccphone.remote.messages.PingPong.Pong(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pongData_ = pongData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.micoli.phone.ccphone.remote.messages.PingPong.Pong) {
          return mergeFrom((org.micoli.phone.ccphone.remote.messages.PingPong.Pong)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.micoli.phone.ccphone.remote.messages.PingPong.Pong other) {
        if (other == org.micoli.phone.ccphone.remote.messages.PingPong.Pong.getDefaultInstance()) return this;
        if (other.hasPongData()) {
          setPongData(other.getPongData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPongData()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              pongData_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes pongData = 1;
      private com.google.protobuf.ByteString pongData_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasPongData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getPongData() {
        return pongData_;
      }
      public Builder setPongData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pongData_ = value;
        onChanged();
        return this;
      }
      public Builder clearPongData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pongData_ = getDefaultInstance().getPongData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Pong)
    }
    
    static {
      defaultInstance = new Pong(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Pong)
  }
  
  public static abstract class PingPongService
      implements com.google.protobuf.Service {
    protected PingPongService() {}
    
    public interface Interface {
      public abstract void ping(
          com.google.protobuf.RpcController controller,
          org.micoli.phone.ccphone.remote.messages.PingPong.Ping request,
          com.google.protobuf.RpcCallback<org.micoli.phone.ccphone.remote.messages.PingPong.Pong> done);
      
      public abstract void fail(
          com.google.protobuf.RpcController controller,
          org.micoli.phone.ccphone.remote.messages.PingPong.Ping request,
          com.google.protobuf.RpcCallback<org.micoli.phone.ccphone.remote.messages.PingPong.Pong> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new PingPongService() {
        @java.lang.Override
        public  void ping(
            com.google.protobuf.RpcController controller,
            org.micoli.phone.ccphone.remote.messages.PingPong.Ping request,
            com.google.protobuf.RpcCallback<org.micoli.phone.ccphone.remote.messages.PingPong.Pong> done) {
          impl.ping(controller, request, done);
        }
        
        @java.lang.Override
        public  void fail(
            com.google.protobuf.RpcController controller,
            org.micoli.phone.ccphone.remote.messages.PingPong.Ping request,
            com.google.protobuf.RpcCallback<org.micoli.phone.ccphone.remote.messages.PingPong.Pong> done) {
          impl.fail(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.ping(controller, (org.micoli.phone.ccphone.remote.messages.PingPong.Ping)request);
            case 1:
              return impl.fail(controller, (org.micoli.phone.ccphone.remote.messages.PingPong.Ping)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.micoli.phone.ccphone.remote.messages.PingPong.Ping.getDefaultInstance();
            case 1:
              return org.micoli.phone.ccphone.remote.messages.PingPong.Ping.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.micoli.phone.ccphone.remote.messages.PingPong.Pong.getDefaultInstance();
            case 1:
              return org.micoli.phone.ccphone.remote.messages.PingPong.Pong.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void ping(
        com.google.protobuf.RpcController controller,
        org.micoli.phone.ccphone.remote.messages.PingPong.Ping request,
        com.google.protobuf.RpcCallback<org.micoli.phone.ccphone.remote.messages.PingPong.Pong> done);
    
    public abstract void fail(
        com.google.protobuf.RpcController controller,
        org.micoli.phone.ccphone.remote.messages.PingPong.Ping request,
        com.google.protobuf.RpcCallback<org.micoli.phone.ccphone.remote.messages.PingPong.Pong> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.micoli.phone.ccphone.remote.messages.PingPong.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.ping(controller, (org.micoli.phone.ccphone.remote.messages.PingPong.Ping)request,
            com.google.protobuf.RpcUtil.<org.micoli.phone.ccphone.remote.messages.PingPong.Pong>specializeCallback(
              done));
          return;
        case 1:
          this.fail(controller, (org.micoli.phone.ccphone.remote.messages.PingPong.Ping)request,
            com.google.protobuf.RpcUtil.<org.micoli.phone.ccphone.remote.messages.PingPong.Pong>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.micoli.phone.ccphone.remote.messages.PingPong.Ping.getDefaultInstance();
        case 1:
          return org.micoli.phone.ccphone.remote.messages.PingPong.Ping.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.micoli.phone.ccphone.remote.messages.PingPong.Pong.getDefaultInstance();
        case 1:
          return org.micoli.phone.ccphone.remote.messages.PingPong.Pong.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends org.micoli.phone.ccphone.remote.messages.PingPong.PingPongService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void ping(
          com.google.protobuf.RpcController controller,
          org.micoli.phone.ccphone.remote.messages.PingPong.Ping request,
          com.google.protobuf.RpcCallback<org.micoli.phone.ccphone.remote.messages.PingPong.Pong> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.micoli.phone.ccphone.remote.messages.PingPong.Pong.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.micoli.phone.ccphone.remote.messages.PingPong.Pong.class,
            org.micoli.phone.ccphone.remote.messages.PingPong.Pong.getDefaultInstance()));
      }
      
      public  void fail(
          com.google.protobuf.RpcController controller,
          org.micoli.phone.ccphone.remote.messages.PingPong.Ping request,
          com.google.protobuf.RpcCallback<org.micoli.phone.ccphone.remote.messages.PingPong.Pong> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.micoli.phone.ccphone.remote.messages.PingPong.Pong.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.micoli.phone.ccphone.remote.messages.PingPong.Pong.class,
            org.micoli.phone.ccphone.remote.messages.PingPong.Pong.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public org.micoli.phone.ccphone.remote.messages.PingPong.Pong ping(
          com.google.protobuf.RpcController controller,
          org.micoli.phone.ccphone.remote.messages.PingPong.Ping request)
          throws com.google.protobuf.ServiceException;
      
      public org.micoli.phone.ccphone.remote.messages.PingPong.Pong fail(
          com.google.protobuf.RpcController controller,
          org.micoli.phone.ccphone.remote.messages.PingPong.Ping request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public org.micoli.phone.ccphone.remote.messages.PingPong.Pong ping(
          com.google.protobuf.RpcController controller,
          org.micoli.phone.ccphone.remote.messages.PingPong.Ping request)
          throws com.google.protobuf.ServiceException {
        return (org.micoli.phone.ccphone.remote.messages.PingPong.Pong) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.micoli.phone.ccphone.remote.messages.PingPong.Pong.getDefaultInstance());
      }
      
      
      public org.micoli.phone.ccphone.remote.messages.PingPong.Pong fail(
          com.google.protobuf.RpcController controller,
          org.micoli.phone.ccphone.remote.messages.PingPong.Ping request)
          throws com.google.protobuf.ServiceException {
        return (org.micoli.phone.ccphone.remote.messages.PingPong.Pong) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.micoli.phone.ccphone.remote.messages.PingPong.Pong.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Ping_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Ping_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Pong_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Pong_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nping.proto\"6\n\004Ping\022\026\n\016processingTime\030\001" +
      " \002(\005\022\026\n\016pongDataLength\030\002 \002(\005\"\030\n\004Pong\022\020\n\010" +
      "pongData\030\001 \002(\0142=\n\017PingPongService\022\024\n\004pin" +
      "g\022\005.Ping\032\005.Pong\022\024\n\004fail\022\005.Ping\032\005.PongB7\n" +
      "(org.micoli.phone.ccphone.remote.message" +
      "sB\010PingPong\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Ping_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Ping_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Ping_descriptor,
              new java.lang.String[] { "ProcessingTime", "PongDataLength", },
              org.micoli.phone.ccphone.remote.messages.PingPong.Ping.class,
              org.micoli.phone.ccphone.remote.messages.PingPong.Ping.Builder.class);
          internal_static_Pong_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Pong_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Pong_descriptor,
              new java.lang.String[] { "PongData", },
              org.micoli.phone.ccphone.remote.messages.PingPong.Pong.class,
              org.micoli.phone.ccphone.remote.messages.PingPong.Pong.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
